### ISSUE TITLE
Project run error

### ISSUE THREAD

**Issue by love381** [feferna/psoCNN#4]
psoCNN 
       __init__ 
             if self.population.particle[i].pBest.acc >= self.gBest_acc[0]:
                print("Found a new gBest.")
                #2 TypeError: can't pickle _thread.RLock objects
                self.gBest = deepcopy(self.population.particle[i])
                self.gBest_acc[0] = self.population.particle[i].pBest.acc
                print("New gBest acc: " + str(self.gBest_acc[0]))
have a error 
            File "D:/jianmo1/psoCNN-master/main.py", line 69, in <module>
                     dropout_rate=dropout)
             File "D:/jianmo1/psoCNN-master\psoCNN.py", line 218, in __init__
                     self.gBest = deepcopy(self.population.particle[i])
TypeError: can't pickle _thread.RLock objects

**Comment by feferna** [comment]
I finally found out what was the problem. It is not a good idea to deepcopy a keras model. Issue is fixed.
