### ISSUE TITLE
Configuration query

### ISSUE THREAD

**Issue by love381** [feferna/psoCNN#6]
I see that the Nvidia GTX 960M mentioned in your paper ran out of results. I would like to ask, what is the running memory of your computer? 8G can't run out of results.

**Comment by feferna** [comment]
The GPU was a 960m with 4 GB of memory, and the computer was a Core i7 with 16 GB of DDR3 memory. You need to reduce the batch size in order to run with a lower memory footprint.

**Comment by love381** [comment]
My computer is 8G DDR3, I will use the image server to try the code

**Comment by VincentSeven1** [comment]
I can't save the best gBest model of “ best_gBest_yaml = pso.gBest.model.to_yaml()”， the error of this program is shown in the figure.
![image](https://user-images.githubusercontent.com/55794458/102838145-6d725980-4438-11eb-98df-fc4635bfa68a.png)
I would be very grateful if it can help me.

**Comment by feferna** [comment]
Please, download the latest version of the code. It should solve your problem.

**Comment by VincentSeven1** [comment]
I will try it, thank you.
